name: node_diary
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  font_awesome_flutter: ^10.12.0
  drift: ^2.32.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.4
  json_annotation: ^4.11.0
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  file_picker: ^10.3.10
  smooth_sheets: ^0.17.0
  geolocator: ^14.0.2
  loading_indicator_m3e: ^0.1.1
  share_plus: ^10.1.4
  widget_screenshot_plus: ^0.0.7
  table_calendar: ^3.2.0
  flutter_svg: ^2.2.4
  url_launcher: ^6.3.2
  archive: ^3.6.1
  local_auth: ^3.0.1
  flutter_quill_to_pdf: ^2.3.9
  pdf: ^3.11.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.12.2
  json_serializable: ^6.13.0
  drift_dev: ^2.32.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app_icon/mingcute_icon.png
    - assets/weather_icons/qweather/
  fonts:
    - family: HarmonyOSSansSC
      fonts:
        - asset: assets/fonts/harmonyos_sans_sc/HarmonyOS_Sans_SC_Regular.ttf
          weight: 400
        - asset: assets/fonts/harmonyos_sans_sc/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500
        - asset: assets/fonts/harmonyos_sans_sc/HarmonyOS_Sans_SC_Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/mingcute_icon.png
