import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive_io.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:node_diary/core/services/backup_zip_reader.dart';
import 'package:path/path.dart' as p;

void main() {
  late Directory root;
  setUp(
    () async =>
        root = await Directory.systemTemp.createTemp('jotsy_zip_compat_'),
  );
  tearDown(() => root.delete(recursive: true));

  test(
    'traditional ZIP encryption with data descriptors remains readable',
    () async {
      // Generated by Info-ZIP zip -P legacy-password, independently of archive.
      const encoded =
          'UEsDBBQACQAIABEASV3kguHSNwAAAJgIAAAKABwAbGVnYWN5LnR4dFVUCQADIb7HaiG+x2p1eAsAAQToAwAABOgDAABxFA9SYmEOGY1aYFxajo7uMt16wUDQW3SSXnnaXtSnf0CgP3KXlsDabQez6fXhqMB/zvQYPwcIUEsHCOSC4dI3AAAAmAgAAFBLAQIeAxQACQAIABEASV3kguHSNwAAAJgIAAAKABgAAAAAAAEAAACkgQAAAABsZWdhY3kudHh0VVQFAAMhvsdqdXgLAAEE6AMAAAToAwAAUEsFBgAAAAABAAEAUAAAAIsAAAAAAA==';
      final zip = await File(
        p.join(root.path, 'legacy.zip'),
      ).writeAsBytes(base64Decode(encoded));
      final output = await Directory(p.join(root.path, 'output')).create();
      BackupZipReader.extract(
        zip.path,
        output.path,
        password: 'legacy-password',
      );
      expect(
        await File(p.join(output.path, 'legacy.txt')).readAsString(),
        List.filled(100, 'legacy backup content\n').join(),
      );
    },
  );

  test(
    'WinZip AE-2 authentication restores entries with zero CRC fields',
    () async {
      final archive = Archive()
        ..addFile(
          ArchiveFile('file.bin', 5, [1, 2, 3, 4, 5])..compress = false,
        );
      final bytes = Uint8List.fromList(
        ZipEncoder(password: 'password').encode(archive)!,
      );
      final decoder = ZipDecoder()..decodeBytes(bytes);
      final fields = ByteData.sublistView(bytes);
      final local = decoder.directory.fileHeaders.single.localHeaderOffset!;
      final central = decoder.directory.centralDirectoryOffset;
      fields.setUint32(local + 14, 0, Endian.little);
      fields.setUint32(central + 16, 0, Endian.little);
      _markAe2(
        fields,
        local + 30 + fields.getUint16(local + 26, Endian.little),
        fields.getUint16(local + 28, Endian.little),
      );
      _markAe2(
        fields,
        central + 46 + fields.getUint16(central + 28, Endian.little),
        fields.getUint16(central + 30, Endian.little),
      );
      final zip = await File(p.join(root.path, 'ae2.zip')).writeAsBytes(bytes);
      final output = await Directory(p.join(root.path, 'output')).create();
      BackupZipReader.extract(zip.path, output.path, password: 'password');
      expect(await File(p.join(output.path, 'file.bin')).readAsBytes(), [
        1,
        2,
        3,
        4,
        5,
      ]);
    },
  );

  test('empty encrypted attachments retain their zero length', () async {
    final archive = Archive()
      ..addFile(ArchiveFile('empty.txt', 0, <int>[])..compress = false);
    final zip = await File(
      p.join(root.path, 'empty.zip'),
    ).writeAsBytes(ZipEncoder(password: 'password').encode(archive)!);
    final output = await Directory(p.join(root.path, 'output')).create();
    BackupZipReader.extract(zip.path, output.path, password: 'password');
    expect(await File(p.join(output.path, 'empty.txt')).length(), 0);
  });
}

void _markAe2(ByteData fields, int offset, int length) {
  final end = offset + length;
  while (offset + 4 <= end) {
    final id = fields.getUint16(offset, Endian.little);
    final size = fields.getUint16(offset + 2, Endian.little);
    if (id == 0x9901) {
      fields.setUint16(offset + 4, 2, Endian.little);
      return;
    }
    offset += size + 4;
  }
  throw StateError('AES metadata is absent from the fixture');
}
